edition: 1.0.0
name: modelscope-app
# access是当前应用所需要的密钥信息配置：
# 密钥配置请参见：https://www.serverless-devs.com/serverless-devs/command/config
# 密钥使用请参见：https://www.serverless-devs.com/serverless-devs/tool
access: {{ access }}

vars: # 全局变量
  region: {{ region }}
  service:
    name: {{ serviceName }}
    description: "modelscope deployment"
    internetAccess: true
    role: {{ roleArn }}
    vpcConfig: auto
    nasConfig: auto

services:
  model_download_func:
    component: 'fc'
    actions:
      post-deploy:
        - component: fc invoke
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: model_download_func
        description: initialize model into nas storage
        handler: index.handler
        timeout: 86400
        memorySize: 2048
        instanceType: e1
        instanceConcurrency: 1
        runtime: python3.9
        codeUri: ./model_download
        environmentVariables:
          MODEL_ID: {{ modelId }}
          MODEL_VERSION: {{ modelRevision }}
          MODELSCOPE_CACHE: /mnt/auto
          MODELSCOPE_TOKEN: {{ accessToken }}
  
  tgpu_basic_func:
    component: 'fc'
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: model_app_func
        description: Deploy ModelScope applications of model {{ modelId }}
        handler: not-used
        timeout: 600
        caPort: 9000
        instanceType: {{ gpuInstanceType }}
        gpuMemorySize: {{ gpuMemorySize }}
        memorySize: {{ memorySize }}
        cpu: 2
        diskSize: 512
        instanceConcurrency: 1
        runtime: custom-container
        customContainerConfig:
          image: registry.${vars.region}.aliyuncs.com/modelscope-repo/modelscope:fc-deploy-common-v2
        environmentVariables:
          MODEL_ID: {{ modelId }}
          MODEL_VERSION: {{ modelRevision }}
          MODELSCOPE_CACHE: /mnt/auto
          MODELSCOPE_TOKEN: {{ accessToken }}
          TASK: {{ task }}

      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT

      # customDomains:
      #   - domainName: auto
      #     protocol: HTTP
      #     routeConfigs:
      #       - path: '/*'
